# Build BASE
FROM node:21.6-alpine as BASE
LABEL author="minhgiang"

WORKDIR /app
COPY package.json  package-lock.json ./
RUN apk add --no-cache git libc6-compat 

# Build Image
FROM node:21.6-alpine AS BUILD
LABEL author="minhgiang"

WORKDIR /app
COPY --from=BASE /app/node_modules ./node_modules
COPY . .
RUN apk add --no-cache git curl \
  && npm run build \
  && cd .next/standalone \
  && node-prune

# Build production
FROM node:21.6-alpine AS PRODUCTION
LABEL author="minhgiang"

WORKDIR /app

COPY --from=BUILD /app/public ./public
COPY --from=BUILD /app/next.config.js ./

# Set mode "standalone" in file "next.config.js"
COPY --from=BUILD /app/.next/standalone ./
COPY --from=BUILD /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]


